### ISSUE TITLE
Handle packages which don't support out of source builds

### ISSUE THREAD

**Issue by andreypopp** [jordwalke/esy#10]
Right now we just make them build within the source directory but with #6 they will fail.

Instead:
* Assume by default packages support out of source builds and respect `$cur__target_dir`. Again #6 will catch the violations here.
* Make an opt-out mechanism for packages which *doesn't* support out of source builds.
* For packages which don't support out of source build we need to copy its sources over to `$cur__target_dir` on each build.

**Comment by jordwalke** [comment]
It's also a requirement for symlinked packages.
