### ISSUE TITLE
Topfind issue

### ISSUE THREAD

**Issue by andreypopp** [jordwalke/esy#21]
This issue is not related directly to Esy but I figured out it would be useful to keep track of it somewhere.

Currently we install ocamlfind with `-no-topfind` because ocamlfind installs it into the OCaml compiler stdlib location which isn't allowed as we may have multiple ocamlfind packages installed for a single ocaml compiler. Moreover when #17 is merged — such behaviour will be caught and build will be failed in such cases.

Without topfind installed the `#use "topfind";` will fail in OCaml toplevel. For example opam packages which depend on `topkg` build system (`astring`, `alcotest`, ...) will fail its build.

What we can do:

1. Patch ocamlfind to install `topfind` into its own `lib/` directory.
2. Make ocamlfind export `OCAML_TOPLEVEL_PATH` env var pointing to its own lib directory. this env var is respected by some tools (for example solvuu-build generates `.ocamlinit` which respects it, unfortunately not `topkg`).
3. Make builds script which use `topkg` execute build with `ocaml -I $OCAML_TOPLEVEL_PATH ...`

**Comment by andreypopp** [comment]
This is also needed for core to be able to install.

**Comment by yunxing** [comment]
hmm, this could be a general issue. 

I think we have other packages that installs themselves into ocaml's stdlib as well, for example, camlp4 installs itself into ocaml's stdlib. Also, all packages with a shared library (ocamlzip, ANSITerminal, lwt) writes to ocaml/lib/ocaml/ld.conf so that the linker can find their localtion during runtime.

**Comment by andreypopp** [comment]
it is going to be fixed by https://github.com/esy-ocaml/ocamlfind/commit/bbe790af2872804326e9157b37f9296914279376

Note that fork isn't required for ocamlfind, just a more complex build script which shims `$OCAMLLIB`.
