### ISSUE TITLE
make: env: Argument list too long

### ISSUE THREAD

**Issue by andreypopp** [jordwalke/esy#28]
It looks like we are hitting the ceil of `make`. Looks like `make` calls shell with `-c` and that triggers the error.

An alternative approach would be to eject into into a directory, then we can place multiple files there — `Makefile` itself, separate shell scripts with env for corresponding packages. I think that also have the advantage of being more observable (it is easier to look into several files of interest rather than go through the 25 KSLOC Makefile).

**Comment by jordwalke** [comment]
I like your suggestion. It also seems we'd want this anyways to make the VSCode-style magic sandbox environment loading happen in all the editors. Editors will look for one of these makefiles that are output, and then source them (somehow) to setup the environment so it can find `refmt`, `ocaml`, `merlin`.
