### ISSUE TITLE
Memoize module resolution

### ISSUE THREAD

**Issue by andreypopp** [jordwalke/esy#29]
Currently than we build sandbox repr in memory — we don't memoize node module resolution results. Try adding `core` (a package with a great number of interdeps) and see perf suffer a lot. I tried a basic memoization and runtime dropped from 30s to <1s.

**Comment by jordwalke** [comment]
> I tried a basic memoization and runtime dropped from 30s to <1s.

WOW.

Also, the environment computation could benefit from memoization I believe.
