### ISSUE TITLE
[HIGH PRI] Perform robust, X-plat string replace on artifacts.

### ISSUE THREAD

**Issue by andreypopp** [jordwalke/esy#31]
#26 introduces dependency on `python`, while `python` is available out of the box on most systems we still want to get rid of it because of perf reasons

**Comment by yunxing** [comment]
Is it possible to use sed here?

**Comment by andreypopp** [comment]
> Is it possible to use sed here?

Not sure. I tried it and it didn't work. Probably we need to convert binary to hex before doing a replacement.

**Comment by jordwalke** [comment]
Clarifying some requirements here:

- Robust, fast string replace that doesn't need python2/perl or any other weird/fragile stuff.
- Cross platform is a plus (or the potential to make it so fairly easily).
- Speed is a plus. C is a good option.
- We need automated test cases.
  - With files with unicode paths in them.
  - Various encoding. I don't even know all the test cases.

@IwanKaramazow was thinking about this.

**Comment by IwanKaramazow** [comment]
A robust c implementation has (temporarily) become the bane of my existence. 😄
I'm having some trouble handling binary files (e.g. `ocamlopt`) atm. Figured out this morning where it's going wrong. Solution with tests are coming.

**Comment by IwanKaramazow** [comment]
Can be closed after merge of https://github.com/reasonml/esy/pull/16 with https://github.com/IwanKaramazow/FastReplaceString/

**Comment by IwanKaramazow** [comment]
Merged & operational :)
Can be closed

**Comment by jordwalke** [comment]
Awesome work. I really like how you created a high quality, well-tested [standalone library](https://github.com/IwanKaramazow/FastReplaceString) out of this - having to reliably replace strings in files is super common. I'm sure many people will get good use out of the utility.
