### ISSUE TITLE
Packages to manually convert over

### ISSUE THREAD

**Issue by jordwalke** [jordwalke/esy#35]
Before doing the full switch to `esy`, we have to convert packages.

[This issue](https://github.com/jordwalke/esy/issues/33) tracks migrating all the automated packages, but we also need to migrate some of the individually crafted packages that used `dependency-env`.

Among them are:

- https://github.com/reasonml/BetterErrors/
- https://github.com/reasonml/rebel/blob/master/package.json
- github.com/facebook/reason

Add any you think of here.

We can try to build support in `esy` for supporting `dependency-env` simultaneously, or we could all block off a few hours at the same time, and just aggressively port everything forward.

**Comment by andreypopp** [comment]
Some comments:

* Reason: https://github.com/andreypopp/reason/tree/esy
* I ported BetterErrors from opam, isn't that enough?
* Rebel is blocked on #28 because of core dep.

**Comment by jordwalke** [comment]
> I ported BetterErrors from `opam`, isn't that enough?

I believe we've fallen out of sync and will likely fall even more out of sync as people rapidly iterate on it.
The `npm` package is probably the authoritative one.

I actually wouldn't mind making `opam` the authoritative store, and syncing entirely in the direction of `npm`, but the turnaround time for publishing to opam was just too long last time I checked. With npm, it's a couple of commands on the CLI.

**Comment by andreypopp** [comment]
Update:

* [x] Reason https://github.com/andreypopp/reason/tree/esy
* [x] BetterErrors https://github.com/esy-ocaml/BetterErrors/tree/esy
* [x] Rebel https://github.com/esy-ocaml/rebel/tree/esy

Not closing because we need to sort out the packaging story yet.

**Comment by andreypopp** [comment]
Changed my mind, let's track it in #33
