### ISSUE TITLE
Make "esy shell" an alias to "esy $SHELL" add "esy pure-shell"

### ISSUE THREAD

**Issue by andreypopp** [jordwalke/esy#8]
Right now `esy shell` is a almost-"pure" shell (almost same env which is used for sandboxed builds). That purity isn't what a user expects when running own commands but something which is valuable when debugging a broken build.

Instead what we should do:
* `esy shell` is an alias to `esy $SHELL` and see #7 for improvements there.
* `esy pure-shell` command is a "pure" shell — it should be exactly the same env which is used for building a package.

**Comment by andreypopp** [comment]
Same should be done regarding to `esy CMD` — it should run `CMD` in a non-pure shell, with user customizations enabled.

**Comment by jordwalke** [comment]
In the mean time, since `esy CMD` scrubs the environment so cleanly, `vim` will fail, and here's the current workaround:

```
esy env SHELL=$SHELL && vim
```
