### ISSUE TITLE
`Lib` folder missing in source code

### ISSUE THREAD

**Issue by omefire** [jordwalke/esy#93]
While reading through `esy build` source code, I found this code piece `require('../lib/esy/bin/esy');` in the file `https://github.com/reasonml/esy/blob/esy/bin/esy.js`.
However, I don't see any `lib` folder in the source tree. 
How do I get ahold of the lib folder and keep scrutinizing the code ?

**Comment by omefire** [comment]
@andreypopp , any ideas ?

**Comment by omefire** [comment]
I did see a lib directory here: `/Users/omefire/.nvm/versions/node/v7.2.1/lib/node_modules/esy/lib/esy/bin/esy.js`.

I don't know whether I can get a local one that's related to my local install.

**Comment by andreypopp** [comment]
@omefire oops, contributing instructions are missing `make build` step — it should produce `lib/` directory. Also there's `make watch` command which starts a watcher which continiously rebuild `lib/` on changes to `src/`.

**Comment by andreypopp** [comment]
I added this to `README.md`.

**Comment by omefire** [comment]
Thanks @andreypopp! Closing this issue then..

**Comment by omefire** [comment]
@andreypopp, Is any of the code in the 'lib' folder in this source code tree ?
