### ISSUE TITLE
Clean Abstraction For Intermediate Build Representation.

### ISSUE THREAD

**Issue by jordwalke** [jordwalke/esy#94]
By abstracting away the build dependencies, we can eject into a variety of different formats including Makefile / Ninja or even node.js. This allows us to integrate with various platforms including Windows.

As a first step, we should just cleanly abstract the build process, and continue to generate a make file for ejecting. Then later, someone can add a JS backend (or ninja).

**Comment by andreypopp** [comment]
Working on it in reasonml/esy#13

**Comment by andreypopp** [comment]
Merged.
