### ISSUE TITLE
A way to prevent sandbox-exec on ejecting.

### ISSUE THREAD

**Issue by jordwalke** [jordwalke/esy#96]
I found a really great use case for ejecting to makefile, and my host has sandbox-exec, but the destination does not. I'm ejecting from mac, and building on linux. I think there should be some way to at least disable sandbox exec when you've ejected. Even a simple hack should do.

**Comment by andreypopp** [comment]
`esy__platform` should be set at runtime and not during the ejection. That should do the trick as it is used to decide which (if any) sandbox mechanism to use.

**Comment by jordwalke** [comment]
"  should be set at runtime "

Just to confirm, you mean set at build time?

I think the ejected makefile needs to have all the rules already in place in the makefile (or js build plan / whatever). Would it then make sense to have an "eject for platform x"?

For more context, I actually needed a makefile eject for this use case because the server I was uploading to had a very old version of node that the esy JS code couldn't work with (it used modern idioms like object spread etc).

**Comment by andreypopp** [comment]
> " should be set at runtime "
>
> Just to confirm, you mean set at build time?

Yes, sorry, I was going to say "build run time".

> I think the ejected makefile needs to have all the rules already in place in the makefile (or js build plan / whatever). Would it then make sense to have an "eject for platform x"?

Generated `Makefile` already has all the rules in it for every supported platform. The only thing which is needed is to move code which inspects current platform and writes it into `esy__platform` from code which ejects build into build runtime itself so ejected build could be distributed to other architectures/platforms.

> For more context, I actually needed a makefile eject for this use case because the server I was uploading to had a very old version of node that the esy JS code couldn't work with (it used modern idioms like object spread etc).

FWIW Object spread should be compiled away with Babel.
