### ISSUE TITLE
Make opam-file-format work with BuckleScript

### ISSUE THREAD

**Issue by wokalski** [jordwalke/esy#98]
`opam-file-format` is a parser for `opam` files. If it is compilable by BuckleScript, we save a lot of time when implementing #81.

If we compile it with Bucklescript we can drop the OCaml dependency and publish a package containing the JS output.

#81 depends on this one.

I have started working on this feature.

**Comment by wokalski** [comment]
This one was trivial. `opam-file-format` works with BuckleScript out of the box. There's some problem with `Pervasives` module.

1. `in_channel` is an argument to `Lexing.from_channel`
2. in the simplest scenario you use `OcamlParser.main` 
3. it takes `lexbuf` as one of its args
4. BuckleScript doesn't implement `open_in` yet.

The parser itself works though so this is a good first step.

The source is here, although it's probably gonna live in the `esy` at the end of the day.
https://github.com/wokalski/opam-file-format-bs

**Comment by wokalski** [comment]
Actually it's not a problem because we can create a `lexbuf` with a `string`. Even if there's no way to read a file into a string in BuckleScript we can resort to `bs.raw`.

**Comment by andreypopp** [comment]
Awesome!

**Comment by IwanKaramazow** [comment]
@wokalski Awesome work!
